### ISSUE TITLE
Webfrontend

### ISSUE THREAD

**Issue by k3x** [991jo/gameserver-rotator#3]
Für den Gast ist nicht sichtbar, welches Soiel jetzt und als nächstes läuft. Dies sollte über eine Webseite einsehbar sein. Die IP des Servers dann am besten per DNS auf über einen schönen Namen erreichbar machen.

**Comment by 991jo** [comment]
the web UI is now available.
The description in the data.json file can contain html markup. Further information, links, IPs, etc. can be added there.
If you are not happy with the web UI and need something that looks a bit more fancy feel free to modify it. Pull requests are welcome.
